name: Build and Deploy

on:
  push:
    branches: [ "main" ]
 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set API key environment variable
        run: echo "API_KEY=$API_KEY" >> $GITHUB_ENV

      - name: Set API key in JS file
        run: sed -i 's/encrypted_api_key/${{ secrets.API_KEY }/g' config.js
        
      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git config --global user.email "tlbs6513@gmail.com"
          git config --global user.name "Lenora Stevens"
          git add .
          git commit -m "Update API key"
          git push
