# This is a basic workflow to help you get started with Actions

name: Build and Deploy

on:
  push:
    branches: [ "main" ]
 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set API key in JS file
        run: sed -i 's/encrypted_api_key/${{ secrets.API_KEY }/g' config.js
